package com.abc.rule.worktask.tipm.tipmTimer

import com.abc.record.Attribute;
import com.abc.record.AttributeFactory;
import com.abc.fuse.attribute.FuseAttribute;
import com.abc.fuse.attribute.FuseMultiAttribute;
import com.abc.query.criteria.Criteria;

import com.zhsq.biz.common.*;
import com.zhsq.biz.constant.worktask.*;
import com.zhsq.biz.worktask.algorithm.*;
import com.zhsq.biz.constant.*;
import com.abc.relation.RecordRelation;
import java.util.Date;

global java.util.List addedLabelList;
global java.util.List removedLabelList;
global java.util.List attributeList;
global java.util.List putFuseMultiAttributeList;
global java.util.List removedMultiAttrList;//根据name删除所有
global java.util.Map removedMultiAttrMap;//根据keyValue和name删除一行
global com.abc.record.RecordCompound recordCompound;

global java.lang.String userCode;
global java.lang.String recordCode;
global java.lang.String entityType;
global  com.abc.complexus.RecordComplexus recordComplexus;
global com.abc.ops.RecordRelationOpsBuilder recordRelationOpsBuilder;

rule "超时任务标记"//处理中的任务进行超时标记
	salience 8
when
	$taskD:FuseAttribute( name==WorkTaskItem.任务状态, value==EnumKeyValue.ENUM_任务状态_处理中);
	$taskE:FuseAttribute( name==WorkTaskItem.任务结束时间,CommonCalculation.isBasicLawful(value));
	$taskF:FuseAttribute( name==WorkTaskItem.任务是否超时,value!=EnumKeyValue.ENUM_是否_是);
	eval(TaskIntrospection.inspectTimeOut($taskE.getValueStrToSql()))
then  
	$taskF.setValue(EnumKeyValue.ENUM_是否_是);
	attributeList.add($taskF);
end

rule "超时任务标记2"//处理中的任务进行超时标记
	salience 8
when
	$taskD:FuseAttribute( name==WorkTaskItem.任务状态, value==EnumKeyValue.ENUM_任务状态_处理中);
	$taskE:FuseAttribute( name==WorkTaskItem.任务结束时间,CommonCalculation.isBasicLawful(value));
	not FuseAttribute(name==WorkTaskItem.任务是否超时);
	eval(TaskIntrospection.inspectTimeOut($taskE.getValueStrToSql()));
then 
	Attribute attribute=AttributeFactory.newInstance(WorkTaskItem.任务是否超时,EnumKeyValue.ENUM_是否_是);
	attributeList.add(attribute);
end

