package com.abc.rule.family.ipm

import com.abc.fuse.improve.attribute.FuseAttribute;
import com.abc.relation.RecordRelation;
import  com.zhsq.biz.constant.people.PeopleItem;
import  com.zhsq.biz.constant.family.FamilyItem;
import com.abc.rrc.record.Attribute;
import com.abc.rrc.factory.AttributeFactory;
import com.zhsq.biz.family.algorithm.DataIntrospection;
import com.zhsq.biz.constant.EnumKeyValue;
import com.zhsq.biz.constant.RelationType;
import com.zhsq.biz.common.OutputDisplay;

global java.lang.String hostCode; 
global java.lang.String hostType;

global java.lang.String userCode;
global java.lang.String recordCode;
global java.lang.String recordName;

global java.util.List attributeList;
global java.util.List addedLabelList;
global java.util.List removedLabelList;
global java.util.List addedLabelList;
global java.util.List putFuseLeafAttributeList;
global java.util.List addedLeafAttrList;
global java.util.Map removedLeafAttrMap;
global com.abc.rrc.record.RootRecord rootRecord;
global  com.abc.fuse.improve.ops.builder.RecordRelationOpsBuilder recordRelationOpsBuilder;
global com.abc.complexus.RecordComplexus recordComplexus;

rule "家庭与人存在户主关系设置户主姓名"
	salience 10 
when
	FuseAttribute( name==FamilyItem.家庭分类, attribute.sqlValue==EnumKeyValue.ENUM_家庭分类_户籍家庭)
	RecordRelation(type==RelationType.RR_家庭信息_户主_人口信息,$peopleCode:right);
 	eval( recordComplexus.getRootRecord($peopleCode) !=null )
 	eval( recordComplexus.getRootRecord($peopleCode).findAttribute(PeopleItem.姓名) !=null )
 	eval(recordComplexus.getRootRecord($peopleCode).findAttribute(PeopleItem.姓名).getValueStr() !=null)
then 	
	//设置户主姓名
	Attribute attr=AttributeFactory.newInstance(FamilyItem.户主姓名, recordComplexus.getRootRecord($peopleCode).findAttribute(PeopleItem.姓名).getValueStr());
	attributeList.add(attr);
end

rule "家庭与人存在户主关系设置户主身份证号"
	salience 10 
when
	FuseAttribute( name==FamilyItem.家庭分类, attribute.sqlValue==EnumKeyValue.ENUM_家庭分类_户籍家庭)
 	RecordRelation(type==RelationType.RR_家庭信息_户主_人口信息,$peopleCode:right);
 	eval( recordComplexus.getRootRecord($peopleCode) !=null )
 	eval( recordComplexus.getRootRecord($peopleCode).findAttribute(PeopleItem.身份证号码) !=null )
 	eval(recordComplexus.getRootRecord($peopleCode).findAttribute(PeopleItem.身份证号码).getValueStr() !=null)
then 
	OutputDisplay.showText(recordComplexus.getRootRecord($peopleCode));
	OutputDisplay.showText( recordComplexus.getRootRecord($peopleCode).findAttribute(PeopleItem.身份证号码));
	OutputDisplay.showText(recordComplexus.getRootRecord($peopleCode).findAttribute(PeopleItem.身份证号码).getValueStr());
	//设置户主身份证号
	Attribute idCode=AttributeFactory.newInstance(FamilyItem.户主身份证号, recordComplexus.getRootRecord($peopleCode).findAttribute(PeopleItem.身份证号码).getValueStr());
	attributeList.add(idCode);
end

rule "家庭与人不存在户主关系设置户主姓名和身份证为空"
	salience 10 
when
	FuseAttribute( name==FamilyItem.家庭分类, attribute.sqlValue==EnumKeyValue.ENUM_家庭分类_户籍家庭)
 	not RecordRelation(type==RelationType.RR_家庭信息_户主_人口信息);
then 
	//设置户主姓名
	Attribute name=AttributeFactory.newInstance(FamilyItem.户主姓名, null);
	attributeList.add(name);
	//设置户主身份证号
	Attribute idCode=AttributeFactory.newInstance(FamilyItem.户主身份证号, null);
	attributeList.add(idCode);
end

rule "设置家庭人口数"
	salience 10 
when
 	exists RecordRelation();
then 
	Integer count = DataIntrospection.getFamilyPeoCount(recordComplexus, hostCode);
	//设置家庭人口数量
	Attribute attr=AttributeFactory.newInstance(FamilyItem.家庭总人数, count);
	attributeList.add(attr);
end
