package com.abc.rule.worktask.tipm.tipmTimer


import com.abc.fuse.improve.attribute.FuseAttribute;
import com.abc.relation.RecordRelation;
import com.zhsq.biz.constant.worktask.WorkTaskItem;
import com.abc.rrc.record.Attribute;
import com.abc.rrc.factory.AttributeFactory;
import com.zhsq.biz.family.algorithm.DataIntrospection;
import com.zhsq.biz.constant.EnumKeyValue;
import com.zhsq.biz.constant.RelationType;
import com.abc.fuse.improve.attribute.leaf.FuseLeafAttribute;
import com.zhsq.biz.common.CommonCalculation;
import com.zhsq.biz.people.algorithm.IDIntrospection;
import com.zhsq.biz.constant.DateUtils;
import com.abc.fuse.improve.attribute.FuseLeafAttrFactory;
import com.zhsq.biz.people.algorithm.BirthdayIntrospection;
import java.util.Date;
import com.zhsq.biz.common.AuthUtil;
import java.util.Collection;
import com.zhsq.biz.constant.BaseConstant;
import com.zhsq.biz.worktask.algorithm.TaskIntrospection;


global java.lang.String hostCode; 
global java.lang.String hostType;

global java.lang.String userCode;
global java.lang.String recordCode;
global java.lang.String recordName;

global java.util.List attributeList;
global java.util.List addedLabelList;
global java.util.List removedLabelList;
global java.util.List addedLabelList;
global java.util.List putFuseLeafAttributeList;
global java.util.List addedLeafAttrList;
global java.util.Map removedLeafAttrMap;
global com.abc.rrc.record.RootRecord rootRecord;
global  com.abc.fuse.improve.ops.builder.RecordRelationOpsBuilder recordRelationOpsBuilder;
global com.abc.complexus.RecordComplexus recordComplexus;

rule "超时任务标记"//处理中的任务进行超时标记
	salience 8
when
	$taskD:FuseAttribute( name==WorkTaskItem.任务状态, value==EnumKeyValue.ENUM_任务状态_处理中);
	$taskE:FuseAttribute( name==WorkTaskItem.任务结束时间,CommonCalculation.isBasicLawful(value));
	$taskF:FuseAttribute( name==WorkTaskItem.任务是否超时,value!=EnumKeyValue.ENUM_是否_是);
	eval(TaskIntrospection.inspectTimeOut($taskE.getValueForShow()))
then  
	Attribute taskF = AttributeFactory.newInstance(WorkTaskItem.任务是否超时, EnumKeyValue.ENUM_是否_是);
	attributeList.add(taskF);
end

rule "超时任务标记2"//处理中的任务进行超时标记
	salience 8
when
	$taskD:FuseAttribute( name==WorkTaskItem.任务状态, value==EnumKeyValue.ENUM_任务状态_处理中);
	$taskE:FuseAttribute( name==WorkTaskItem.任务结束时间,CommonCalculation.isBasicLawful(value));
	not FuseAttribute(name==WorkTaskItem.任务是否超时);
	eval(TaskIntrospection.inspectTimeOut($taskE.getValueForShow()));
then 
	Attribute attribute=AttributeFactory.newInstance(WorkTaskItem.任务是否超时,EnumKeyValue.ENUM_是否_是);
	attributeList.add(attribute);
end
