package com.abc.rule.people.tipm

import com.abc.fuse.improve.attribute.FuseAttribute;
import com.abc.fuse.improve.attribute.OpsAttribute;
import com.abc.fuse.improve.attribute.OpsRecordRelation;
import com.abc.fuse.improve.attribute.leaf.OpsLeafAttribute;
import com.abc.relation.RecordRelation;
import com.abc.fuse.improve.attribute.AddedRecordRelation;
import  com.zhsq.biz.constant.people.PeopleItem;
import  com.zhsq.biz.constant.family.FamilyItem;
import com.abc.rrc.record.Attribute;
import com.abc.rrc.factory.AttributeFactory;
import com.zhsq.biz.family.algorithm.DataIntrospection;
import com.zhsq.biz.constant.EnumKeyValue;
import com.zhsq.biz.constant.RelationType;
import com.abc.fuse.improve.attribute.leaf.FuseLeafAttribute;
import com.zhsq.biz.common.CommonCalculation;
import com.zhsq.biz.people.algorithm.IDIntrospection;
import com.zhsq.biz.constant.DateUtils;
import com.zhsq.biz.constant.BaseConstant;
import com.abc.relation.RelationCorrelation;
import com.abc.fuse.improve.attribute.FuseLeafAttrFactory;
import com.zhsq.biz.people.algorithm.IDIntrospection;


global java.lang.String hostCode; 
global java.lang.String hostType;

global java.lang.String userCode;
global java.lang.String recordCode;
global java.lang.String recordName;

global java.util.List attributeList;
global java.util.List addedLabelList;
global java.util.List removedLabelList;
global java.util.List addedLabelList;
global java.util.List putFuseLeafAttributeList;
global java.util.List addedLeafAttrList;
global java.util.Map removedLeafAttrMap;
global com.abc.rrc.record.RootRecord rootRecord;
global  com.abc.fuse.improve.ops.builder.RecordRelationOpsBuilder recordRelationOpsBuilder;
global com.abc.complexus.RecordComplexus recordComplexus;

rule "记录之前就业形式"
	when
		OpsAttribute( name==PeopleItem.就业形式,$opsValue:sqlValue)
		$fuseJOB: FuseAttribute( name== PeopleItem.就业形式,$fuseValue:sqlValue)
		eval(!$opsValue.equals($fuseValue))
	then
		Attribute jobType = AttributeFactory.newInstance(PeopleItem.之前就业形式, $fuseJOB.getValueForShow());
		attributeList.add(jobType);
end

