package com.abc.rule.xfjd.people.ripm

import java.util.Collection;
import java.util.Date;

import com.abc.record.Attribute;
import com.abc.record.AttributeFactory;
import com.abc.fuse.attribute.FuseAttribute;
import com.abc.fuse.attribute.FuseMultiAttribute;
import com.abc.relation.RecordRelation;
import com.abc.auth.AuthHelper;

import com.zhsq.biz.constant.people.*;
import com.zhsq.biz.constant.*;
import com.zhsq.biz.common.*;


global java.lang.String userCode;
global java.lang.String recordCode;
global java.lang.String entityType;
global  com.abc.complexus.RecordComplexus recordComplexus;
global com.abc.ops.RecordRelationOpsBuilder recordRelationOpsBuilder;

rule "无正確社区信息权限"
	salience 10 
when
 not FuseAttribute(name==PeopleItem.所属社区);
then
recordRelationOpsBuilder.putRelation(RelationType.RR_人口信息_可被访问_权限,AuthAlgorithm.getNoAreaAuthCode());
end

rule "移除原社区数据访问"
	salience 10 
when
 $areaFA:FuseAttribute(name==PeopleItem.所属社区,$areaValue:value);
 RecordRelation(type==RelationType.RR_人口信息_可被访问_权限,$oldauth:right,AuthHelper.isMatchedAuthAndLabel($oldauth,EnumKeyValue.ENUM_权限标签_社区数据访问),$oldauth!=AuthAlgorithm.getAreaAuthCode((Integer)$areaValue));
then
	recordRelationOpsBuilder.removeRelation(RelationType.RR_人口信息_可被访问_权限,$oldauth);
end

rule "添加社区数据访问"
	salience 10 
when
 $areaFA:FuseAttribute(name==PeopleItem.所属社区,$areaValue:value);
not RecordRelation(type==RelationType.RR_人口信息_可被访问_权限,$oldauth:right,AuthHelper.isMatchedAuthAndLabel($oldauth,EnumKeyValue.ENUM_权限标签_社区数据访问),$oldauth==AuthAlgorithm.getAreaAuthCode((Integer)$areaValue));
then
	recordRelationOpsBuilder.putRelation(RelationType.RR_人口信息_可被访问_权限,AuthAlgorithm.getAreaAuthCode((Integer)$areaValue));
end



 