package com.abc.rule.family.postimp

import com.abc.fuse.improve.attribute.FuseAttribute;
import com.abc.fuse.improve.attribute.OpsAttribute;
import com.abc.fuse.improve.attribute.OpsRecordRelation;
import com.abc.relation.RecordRelation;
import com.abc.fuse.improve.attribute.AddedRecordRelation;
import com.zhsq.biz.constant.people.PeopleItem;
import  com.zhsq.biz.constant.family.FamilyItem;
import com.abc.rrc.record.Attribute;
import com.abc.rrc.factory.AttributeFactory;
import com.zhsq.biz.family.algorithm.DataIntrospection;
import com.zhsq.biz.constant.EnumKeyValue;
import com.zhsq.biz.constant.RelationType;
import com.abc.fuse.improve.attribute.leaf.FuseLeafAttribute;
import com.zhsq.biz.common.CommonCalculation;
import com.zhsq.biz.people.algorithm.IDIntrospection;
import com.zhsq.biz.constant.DateUtils;
import com.zhsq.biz.constant.BaseConstant;
import com.abc.relation.RelationCorrelation;
import com.abc.util.CodeManager;
import com.abc.util.ValueType;
import com.abc.fuse.improve.attribute.FuseLeafAttrFactory;

global java.lang.String hostCode; 
global java.lang.String hostType;

global java.lang.String userCode;
global java.lang.String recordCode;
global java.lang.String recordName;

global java.util.List attributeList;
global java.util.List addedLabelList;
global java.util.List removedLabelList;
global java.util.List addedLabelList;
global java.util.List putFuseLeafAttributeList;
global java.util.List addedLeafAttrList;
global java.util.Map removedLeafAttrMap;
global com.abc.rrc.record.RootRecord rootRecord;
global  com.abc.ops.builder.RecordRelationOpsBuilder recordRelationOpsBuilder;
global com.abc.complexus.RecordComplexus recordComplexus;


rule "清空家庭错误"
	salience 7
when
   $fa: FuseLeafAttribute(name==FamilyItem.家庭错误信息_错误类型);
then  
	removedLeafAttrMap.put($fa.getLeafCode(), $fa.getName());
end 

rule "家庭没有户主"
	salience 6
when
	$value :FuseAttribute( name==FamilyItem.户籍地址)
	FuseAttribute( name==FamilyItem.家庭分类, sqlValue==EnumKeyValue.ENUM_家庭分类_户籍家庭)
 	not RecordRelation(type == RelationType.RR_家庭信息_户主_人口信息);
then 
	String code = CodeManager.newCode32();
	FuseLeafAttribute leafAttr = FuseLeafAttrFactory.newInstance($value.getCode(), FamilyItem.家庭错误信息, code, FamilyItem.家庭错误信息_错误类型, EnumKeyValue.ENUM_错误类型_家庭信息错误);
	putFuseLeafAttributeList.add(leafAttr);
	FuseLeafAttribute leafAttr2 = FuseLeafAttrFactory.newInstance($value.getCode(), FamilyItem.家庭错误信息, code, FamilyItem.家庭错误信息_描述, "家庭没有户主");
	putFuseLeafAttributeList.add(leafAttr2);
end

rule "家庭有户主但是和户主关系不是户主"
	salience 6
when
	FuseAttribute( name==FamilyItem.家庭分类, sqlValue==EnumKeyValue.ENUM_家庭分类_户籍家庭)
	$value :FuseAttribute( name==FamilyItem.户籍地址 )
 	 RecordRelation(type == RelationType.RR_家庭信息_户主_人口信息, $huzCode:right);
 	 eval(recordComplexus.getRootRecord($huzCode) != null)
 	 eval( recordComplexus.getRootRecord($huzCode).findAttribute(PeopleItem.和户主关系) !=null)
 	 eval(!String.valueOf(EnumKeyValue.ENUM_和户主关系_户主).equals(String.valueOf(recordComplexus.getRootRecord($huzCode).findAttribute(PeopleItem.和户主关系).getSqlValue())) )
then 
	String code = CodeManager.newCode32();
	FuseLeafAttribute leafAttr = FuseLeafAttrFactory.newInstance($value.getCode(), FamilyItem.家庭错误信息, code, FamilyItem.家庭错误信息_错误类型, EnumKeyValue.ENUM_错误类型_家庭信息错误);
	putFuseLeafAttributeList.add(leafAttr);
	FuseLeafAttribute leafAttr2 = FuseLeafAttrFactory.newInstance($value.getCode(), FamilyItem.家庭错误信息, code, FamilyItem.家庭错误信息_描述, "家庭有户主但是和户主关系不是户主");
	putFuseLeafAttributeList.add(leafAttr2);
end

rule "家庭中户主大于一个"
	salience 6
when
	FuseAttribute( name==FamilyItem.家庭分类, sqlValue==EnumKeyValue.ENUM_家庭分类_户籍家庭)
	$value :FuseAttribute( name==FamilyItem.户籍地址 )
 	RecordRelation(type == RelationType.RR_家庭信息_户主_人口信息, $left:left);
 	eval(DataIntrospection.getHzCount(recordComplexus, recordName, $left)>1 )
then 
	String code = CodeManager.newCode32();
	FuseLeafAttribute leafAttr = FuseLeafAttrFactory.newInstance($value.getCode(), FamilyItem.家庭错误信息, code, FamilyItem.家庭错误信息_错误类型, EnumKeyValue.ENUM_错误类型_家庭信息错误);
	putFuseLeafAttributeList.add(leafAttr);
	FuseLeafAttribute leafAttr2 = FuseLeafAttrFactory.newInstance($value.getCode(), FamilyItem.家庭错误信息, code, FamilyItem.家庭错误信息_描述, "家庭中户主大于一个");
	putFuseLeafAttributeList.add(leafAttr2);
end

rule "家庭与人存在户主关系判断户籍地址是否相同"
	salience 10 
when
	FuseAttribute( name==FamilyItem.家庭分类, attribute.sqlValue==EnumKeyValue.ENUM_家庭分类_户籍家庭)
	$value: FuseAttribute(name==FamilyItem.户籍地址, $famAdreValue:sqlValue)
 	RecordRelation(type==RelationType.RR_家庭信息_户主_人口信息,$peopleCode:right)
 	eval( recordComplexus.getRootRecord($peopleCode) !=null )
 	eval( recordComplexus.getRootRecord($peopleCode).findAttribute(PeopleItem.户籍所在地) !=null )
 	eval(recordComplexus.getRootRecord($peopleCode).findAttribute(PeopleItem.户籍所在地).getValueStr() !=null)
 	eval(!recordComplexus.getRootRecord($peopleCode).findAttribute(PeopleItem.户籍所在地).getValueStr().equals($famAdreValue))
then 
	String code = CodeManager.newCode32();
	FuseLeafAttribute leafAttr = FuseLeafAttrFactory.newInstance($value.getCode(), FamilyItem.家庭错误信息, code, FamilyItem.家庭错误信息_错误类型, EnumKeyValue.ENUM_错误类型_家庭信息错误);
	putFuseLeafAttributeList.add(leafAttr);
	FuseLeafAttribute leafAttr2 = FuseLeafAttrFactory.newInstance($value.getCode(), FamilyItem.家庭错误信息, code, FamilyItem.家庭错误信息_描述, "家庭和户主-户籍所在地不同");
	putFuseLeafAttributeList.add(leafAttr2);
end

rule "家庭与人存在成员关系判断户籍地址是否相同"
	salience 10 
when
	FuseAttribute( name==FamilyItem.家庭分类, attribute.sqlValue==EnumKeyValue.ENUM_家庭分类_户籍家庭)
	$value: FuseAttribute(name==FamilyItem.户籍地址, $famAdreValue:sqlValue)
 	RecordRelation(type==RelationType.RR_家庭信息_成员_人口信息,$peopleCode:right)
 	eval( recordComplexus.getRootRecord($peopleCode) !=null )
 	eval( recordComplexus.getRootRecord($peopleCode).findAttribute(PeopleItem.户籍所在地) !=null )
 	eval(recordComplexus.getRootRecord($peopleCode).findAttribute(PeopleItem.户籍所在地).getValueStr() !=null)
 	eval(!recordComplexus.getRootRecord($peopleCode).findAttribute(PeopleItem.户籍所在地).getValueStr().equals($famAdreValue))
then 
	String code = CodeManager.newCode32();
	FuseLeafAttribute leafAttr = FuseLeafAttrFactory.newInstance($value.getCode(), FamilyItem.家庭错误信息, code, FamilyItem.家庭错误信息_错误类型, EnumKeyValue.ENUM_错误类型_家庭信息错误);
	putFuseLeafAttributeList.add(leafAttr);
	FuseLeafAttribute leafAttr2 = FuseLeafAttrFactory.newInstance($value.getCode(), FamilyItem.家庭错误信息, code, FamilyItem.家庭错误信息_描述, "家庭和成员-户籍所在地不同");
	putFuseLeafAttributeList.add(leafAttr2);
end

