package com.abc.rule.people.ipm.ipmTimer


import com.abc.fuse.improve.attribute.FuseAttribute;
import com.abc.relation.RecordRelation;
import  com.zhsq.biz.constant.people.PeopleItem;
import  com.zhsq.biz.constant.family.FamilyItem;
import com.abc.rrc.record.Attribute;
import com.abc.rrc.factory.AttributeFactory;
import com.zhsq.biz.family.algorithm.DataIntrospection;
import com.zhsq.biz.constant.EnumKeyValue;
import com.zhsq.biz.constant.RelationType;
import com.abc.fuse.improve.attribute.leaf.FuseLeafAttribute;
import com.zhsq.biz.common.CommonCalculation;
import com.zhsq.biz.people.algorithm.IDIntrospection;
import com.zhsq.biz.constant.DateUtils;
import com.abc.fuse.improve.attribute.FuseLeafAttrFactory;
import com.zhsq.biz.people.algorithm.BirthdayIntrospection;
global java.lang.String hostCode; 
global java.lang.String hostType;

global java.lang.String userCode;
global java.lang.String recordCode;
global java.lang.String recordName;

global java.util.List attributeList;
global java.util.List addedLabelList;
global java.util.List removedLabelList;
global java.util.List addedLabelList;
global java.util.List putFuseLeafAttributeList;
global java.util.List addedLeafAttrList;
global java.util.Map removedLeafAttrMap;
global com.abc.rrc.record.RootRecord rootRecord;
global  com.abc.fuse.improve.ops.builder.RecordRelationOpsBuilder recordRelationOpsBuilder;
global com.abc.complexus.RecordComplexus recordComplexus;


rule "小于60岁去除所有老人标签"
	salience 8
when
	$nameA:FuseAttribute(name==PeopleItem.出生日期, CommonCalculation.isBasicLawful(value));
	eval(BirthdayIntrospection.extractAge($nameA.getValueForShow())<60);
then 
	removedLabelList.add(EnumKeyValue.ENUM_人口标签_60_69老人);
	removedLabelList.add(EnumKeyValue.ENUM_人口标签_70_79老人);
	removedLabelList.add(EnumKeyValue.ENUM_人口标签_80_89岁老人);
	removedLabelList.add(EnumKeyValue.ENUM_人口标签_90以上岁老人);
	
	Attribute attribute=AttributeFactory.newInstance(PeopleItem.几岁老人, null);
	attributeList.add(attribute);
end

rule "60-69岁老人"
	salience 8
when
	$nameA:FuseAttribute(name==PeopleItem.出生日期, CommonCalculation.isBasicLawful(value));
	eval(BirthdayIntrospection.extractAge($nameA.getValueForShow())>=60 && BirthdayIntrospection.extractAge($nameA.getValueForShow()) <=69);
then 
	addedLabelList.add(EnumKeyValue.ENUM_人口标签_60_69老人);
	removedLabelList.add(EnumKeyValue.ENUM_人口标签_70_79老人);
	removedLabelList.add(EnumKeyValue.ENUM_人口标签_80_89岁老人);
	removedLabelList.add(EnumKeyValue.ENUM_人口标签_90以上岁老人);
	
	Attribute attribute=AttributeFactory.newInstance(PeopleItem.几岁老人, EnumKeyValue.ENUM_老人标签_60_69岁老人);
	attributeList.add(attribute);
end

rule "70-79岁老人"
	salience 8
when
	$nameA:FuseAttribute(name==PeopleItem.出生日期, CommonCalculation.isBasicLawful(value));
	eval(BirthdayIntrospection.extractAge($nameA.getValueForShow())>=70 && BirthdayIntrospection.extractAge($nameA.getValueForShow()) <=79);
then 
	removedLabelList.add(EnumKeyValue.ENUM_人口标签_60_69老人);
	addedLabelList.add(EnumKeyValue.ENUM_人口标签_70_79老人);
	removedLabelList.add(EnumKeyValue.ENUM_人口标签_80_89岁老人);
	removedLabelList.add(EnumKeyValue.ENUM_人口标签_90以上岁老人);
	
	Attribute attribute=AttributeFactory.newInstance(PeopleItem.几岁老人, EnumKeyValue.ENUM_老人标签_70_79岁老人);
	attributeList.add(attribute);
end

rule "80-89岁老人"
	salience 8
when
	$nameA:FuseAttribute(name==PeopleItem.出生日期, CommonCalculation.isBasicLawful(value));
	eval(BirthdayIntrospection.extractAge($nameA.getValueForShow())>=80 && BirthdayIntrospection.extractAge($nameA.getValueForShow()) <=89);
then 
	removedLabelList.add(EnumKeyValue.ENUM_人口标签_60_69老人);
	removedLabelList.add(EnumKeyValue.ENUM_人口标签_70_79老人);
	addedLabelList.add(EnumKeyValue.ENUM_人口标签_80_89岁老人);
	removedLabelList.add(EnumKeyValue.ENUM_人口标签_90以上岁老人);
	
	Attribute attribute=AttributeFactory.newInstance(PeopleItem.几岁老人, EnumKeyValue.ENUM_老人标签_80_89岁老人);
	attributeList.add(attribute);
end

rule "90岁以上老人"
	salience 8
when
	$nameA:FuseAttribute(name==PeopleItem.出生日期, CommonCalculation.isBasicLawful(value));
	eval(BirthdayIntrospection.extractAge($nameA.getValueForShow())>=90);
then 
	removedLabelList.add(EnumKeyValue.ENUM_人口标签_60_69老人);
	removedLabelList.add(EnumKeyValue.ENUM_人口标签_70_79老人);
	removedLabelList.add(EnumKeyValue.ENUM_人口标签_80_89岁老人);
	addedLabelList.add(EnumKeyValue.ENUM_人口标签_90以上岁老人);
	
	Attribute attribute=AttributeFactory.newInstance(PeopleItem.几岁老人, EnumKeyValue.ENUM_老人标签_90岁以上老人);
	attributeList.add(attribute);
end

 