package com.zhsq.rule.people.check

import com.abc.fuse.attribute.FuseAttribute;
import com.abc.fuse.attribute.FuseMultiAttribute;
import com.abc.query.criteria.Criteria;
import com.zhsq.biz.constant.people.*;
import com.zhsq.biz.people.algorithm.IDIntrospection;
import com.zhsq.biz.common.*;
import com.zhsq.biz.constant.*;

import com.abc.fuse.ErrorMessage;
import com.zhsq.biz.constant.MessageCodeConstant;

global java.lang.String entityType;
global  com.abc.complexus.RecordComplexus recordComplexus;

rule "身份证校验错误"
	salience 10
when
    $idtype:FuseMultiAttribute(name==PeopleItem.证件信息_证件类型,value==EnumKeyValue.ENUM_证件类型_身份证,$keyValue:keyValue);
    $idValue:FuseMultiAttribute(name==PeopleItem.证件信息_证件号码,keyValue==$keyValue,CommonCalculation.isBasicLawful(value));
    eval(!IDIntrospection.inspectId($idValue.getValueStrToSql()));
then 
	ErrorMessage errorMessage=new ErrorMessage();
 	errorMessage.setFuseAttribute($idValue);
 	errorMessage.setCode(MessageCodeConstant.ERR1001);
 	errorMessage.setContent(MessageCodeConstant.getName(MessageCodeConstant.ERR1001));
 	insert(errorMessage);
end

rule "身份证号出生日期与出生日期属性是否一致"
	salience 9
when 
	
    $idtype1:FuseMultiAttribute(name==PeopleItem.证件信息_证件类型,value==EnumKeyValue.ENUM_证件类型_身份证,$keyValue:keyValue);
    $idValue1:FuseMultiAttribute(name==PeopleItem.证件信息_证件号码,keyValue==$keyValue,CommonCalculation.isBasicLawful(value));
   	$birthday: FuseAttribute(name==PeopleItem.出生日期 ,CommonCalculation.isBasicLawful(value))
    eval(!IDIntrospection.inspectBirthday($idValue1.getValueStrToSql(), $birthday.getValueStrToSql()));
then
	ErrorMessage errorMessage1=new ErrorMessage();
 	errorMessage1.setFuseAttribute($birthday);
 	errorMessage1.setCode(MessageCodeConstant.ERR1007);
 	errorMessage1.setContent(MessageCodeConstant.getName(MessageCodeConstant.ERR1007));
 	insert(errorMessage1);
end

rule "身份证号性别与性别属性是否一致"
	salience 9
when
    $idtype2:FuseMultiAttribute(name==PeopleItem.证件信息_证件类型,value==EnumKeyValue.ENUM_证件类型_身份证,$keyValue:keyValue);
    $idValue2:FuseMultiAttribute(name==PeopleItem.证件信息_证件号码,keyValue==$keyValue,CommonCalculation.isBasicLawful(value));
   	$sex: FuseAttribute(name==PeopleItem.性别 ,CommonCalculation.isBasicLawful(value))
    eval(!IDIntrospection.inspectSex($idValue2.getValueStrToSql(), $sex.getValueStrToSql()));
then
	ErrorMessage errorMessage2=new ErrorMessage();
 	errorMessage2.setFuseAttribute($sex);
 	errorMessage2.setCode(MessageCodeConstant.ERR1009);
 	errorMessage2.setContent(MessageCodeConstant.getName(MessageCodeConstant.ERR1009));
 	insert(errorMessage2);
end

query "query error message" () 

  errorMessage : ErrorMessage()

end



