package com.abc.rule.worktask.ripm

import java.util.Collection;
import java.util.Date;

import com.abc.record.Attribute;
import com.abc.record.AttributeFactory;
import com.abc.fuse.attribute.FuseAttribute;
import com.abc.fuse.attribute.FuseMultiAttribute;
import com.abc.relation.RecordRelation;

import com.zhsq.biz.common.*;
import com.zhsq.biz.constant.worktask.*;
import com.zhsq.biz.worktask.algorithm.*;
import com.zhsq.biz.constant.BaseConstant;
import com.zhsq.biz.constant.*;

global java.lang.String userCode;
global java.lang.String recordCode;
global java.lang.String entityType;
global  com.abc.complexus.RecordComplexus recordComplexus;
global com.abc.ops.RecordRelationOpsBuilder recordRelationOpsBuilder;

rule "设置创建人及数据的基本权限"
	salience 10 
when
    not RecordRelation( type==RelationType.RR_工作任务_创建人_用户);
then

	recordRelationOpsBuilder.putRelation(RelationType.RR_工作任务_创建人_用户,userCode);
	Collection<String> auths=AuthUtil.getUserAuth((String)userCode,(String)BaseConstant.LABEL_AUTH_工作任务管理类);
	if(auths!=null){
		for(String auth:auths){
			recordRelationOpsBuilder.putRelation(RelationType.RR_工作任务_访问_权限,auth);
		}
	}
	
end

rule "认领任务设置任务执行人"
	salience 10 
when
    not RecordRelation( type==RelationType.RR_工作任务_任务执行人_用户);
    FuseAttribute( name==WorkTaskItem.是否认领任务, CommonCalculation.isBasicLawful(value), value==EnumKeyValue.ENUM_是否_是)
then
	recordRelationOpsBuilder.putRelation(RelationType.RR_工作任务_任务执行人_用户,userCode);
end

 