package com.abc.rule.worktask.tipm

import com.abc.fuse.improve.attribute.FuseAttribute;
import com.abc.relation.RecordRelation;
import com.zhsq.biz.constant.worktask.WorkTaskItem;
import com.abc.rrc.record.Attribute;
import com.abc.rrc.factory.AttributeFactory;
import com.zhsq.biz.family.algorithm.DataIntrospection;
import com.zhsq.biz.constant.EnumKeyValue;
import com.zhsq.biz.constant.RelationType;
import com.abc.fuse.improve.attribute.leaf.FuseLeafAttribute;
import com.zhsq.biz.common.CommonCalculation;
import com.zhsq.biz.people.algorithm.IDIntrospection;
import com.zhsq.biz.constant.DateUtils;
import com.abc.fuse.improve.attribute.FuseLeafAttrFactory;
import com.zhsq.biz.people.algorithm.BirthdayIntrospection;
import java.util.Date;
import com.zhsq.biz.common.AuthUtil;


global java.lang.String hostCode; 
global java.lang.String hostType;

global java.lang.String userCode;
global java.lang.String recordCode;
global java.lang.String recordName;

global java.util.List attributeList;
global java.util.List addedLabelList;
global java.util.List removedLabelList;
global java.util.List addedLabelList;
global java.util.List putFuseLeafAttributeList;
global java.util.List addedLeafAttrList;
global java.util.Map removedLeafAttrMap;
global com.abc.rrc.record.RootRecord rootRecord;
global  com.abc.fuse.improve.ops.builder.RecordRelationOpsBuilder recordRelationOpsBuilder;
global com.abc.complexus.RecordComplexus recordComplexus;

rule "新建任务设置"
	salience 20 
when
	 FuseAttribute( name==WorkTaskItem.任务状态, value==EnumKeyValue.ENUM_任务状态_新建);
then 
	//设置任务创建人
	Attribute attribute=AttributeFactory.newInstance(WorkTaskItem.创建人,AuthUtil.getUserName(userCode));
	attributeList.add(attribute);
end

rule "派发任务"
	salience 18
when
    $attr:FuseAttribute( name==WorkTaskItem.保存派发, value==EnumKeyValue.ENUM_保存派发_派发);
	$statu: FuseAttribute( name==WorkTaskItem.任务状态, value==EnumKeyValue.ENUM_任务状态_新建);
then
	Attribute statu=AttributeFactory.newInstance(WorkTaskItem.任务状态,EnumKeyValue.ENUM_任务状态_处理中);
	 Attribute attribute=AttributeFactory.newInstance(WorkTaskItem.派发时间,new Date());
	attributeList.add(statu);
	attributeList.add(attribute);
end

rule "任务有执行人设置任务领用为否"
	salience 10 
when
    RecordRelation( type==RelationType.RR_工作任务_任务执行人_用户);
    $nameFA: FuseAttribute( name==WorkTaskItem.是否需要领用, CommonCalculation.isBasicLawful(value), value==EnumKeyValue.ENUM_是否_是)
then 
	Attribute nameFA=AttributeFactory.newInstance(WorkTaskItem.是否需要领用,EnumKeyValue.ENUM_是否_否);
	attributeList.add(nameFA);
end
