package com.abc.rule.worktask.ripm

import com.abc.fuse.improve.attribute.FuseAttribute;
import com.abc.relation.RecordRelation;
import com.zhsq.biz.constant.worktask.WorkTaskItem;
import com.abc.rrc.record.Attribute;
import com.abc.rrc.factory.AttributeFactory;
import com.zhsq.biz.family.algorithm.DataIntrospection;
import com.zhsq.biz.constant.EnumKeyValue;
import com.zhsq.biz.constant.RelationType;
import com.abc.fuse.improve.attribute.leaf.FuseLeafAttribute;
import com.zhsq.biz.common.CommonCalculation;
import com.zhsq.biz.people.algorithm.IDIntrospection;
import com.zhsq.biz.constant.DateUtils;
import com.abc.fuse.improve.attribute.FuseLeafAttrFactory;
import com.zhsq.biz.people.algorithm.BirthdayIntrospection;
import java.util.Date;
import com.zhsq.biz.common.AuthUtil;
import java.util.Collection;
import com.zhsq.biz.constant.BaseConstant;


global java.lang.String hostCode; 
global java.lang.String hostType;

global java.lang.String userCode;
global java.lang.String recordCode;
global java.lang.String recordName;

global java.util.List attributeList;
global java.util.List addedLabelList;
global java.util.List removedLabelList;
global java.util.List addedLabelList;
global java.util.List putFuseLeafAttributeList;
global java.util.List addedLeafAttrList;
global java.util.Map removedLeafAttrMap;
global com.abc.rrc.record.RootRecord rootRecord;
global  com.abc.fuse.improve.ops.builder.RecordRelationOpsBuilder recordRelationOpsBuilder;
global com.abc.complexus.RecordComplexus recordComplexus;

rule "设置创建人及数据的基本权限"
	salience 10 
when
    not RecordRelation( type==RelationType.RR_工作任务_创建人_用户);
then

	recordRelationOpsBuilder.putRelation(RelationType.RR_工作任务_创建人_用户,userCode);
	Collection<String> auths=AuthUtil.getUserAuth((String)userCode,(String)BaseConstant.LABEL_AUTH_工作任务管理类);
	if(auths!=null){
		for(String auth:auths){
			recordRelationOpsBuilder.putRelation(RelationType.RR_工作任务_访问_权限,auth);
		}
	}
	
end

rule "认领任务设置任务执行人"
	salience 10 
when
    not RecordRelation( type==RelationType.RR_工作任务_任务执行人_用户);
    FuseAttribute( name==WorkTaskItem.是否认领任务, CommonCalculation.isBasicLawful(value), value==EnumKeyValue.ENUM_是否_是)
then
	recordRelationOpsBuilder.putRelation(RelationType.RR_工作任务_任务执行人_用户,userCode);
end

 