package com.abc.rule.people.ipm

import com.abc.fuse.improve.attribute.FuseAttribute;
import com.abc.relation.RecordRelation;
import  com.zhsq.biz.constant.people.PeopleItem;
import  com.zhsq.biz.constant.family.FamilyItem;
import com.abc.rrc.record.Attribute;
import com.abc.rrc.factory.AttributeFactory;
import com.zhsq.biz.family.algorithm.DataIntrospection;
import com.zhsq.biz.constant.EnumKeyValue;
import com.zhsq.biz.constant.RelationType;
import com.abc.fuse.improve.attribute.leaf.FuseLeafAttribute;
import com.zhsq.biz.common.CommonCalculation;
import com.zhsq.biz.people.algorithm.IDIntrospection;
import com.zhsq.biz.constant.DateUtils;
import com.abc.fuse.improve.attribute.FuseLeafAttrFactory;
import com.zhsq.biz.common.OutputDisplay;
import com.zhsq.biz.common.AuthAlgorithm;
import com.abc.fuse.improve.attribute.label.FuseLabelAttribute;


global java.lang.String hostCode; 
global java.lang.String hostType;

global java.lang.String userCode;
global java.lang.String recordCode;
global java.lang.String recordName;

global java.util.List attributeList;
global java.util.List addedLabelList;
global java.util.List removedLabelList;
global java.util.List addedLabelList;
global java.util.List putFuseLeafAttributeList;
global java.util.List addedLeafAttrList;
global java.util.Map removedLeafAttrMap;
global com.abc.rrc.record.RootRecord rootRecord;
global  com.abc.fuse.improve.ops.builder.RecordRelationOpsBuilder recordRelationOpsBuilder;
global com.abc.complexus.RecordComplexus recordComplexus;

/*
rule "删除居家养老补助标签"
	salience 15
when
	FuseLabelAttribute(value==EnumKeyValue.ENUM_人口标签_居家养老补助);
	not FuseLeafAttribute(name==PeopleItem.老人补助信息_补助类型, sqlValue==EnumKeyValue.ENUM_老人补助枚举_居家养老补助);
then 
	removedLabelList.add(EnumKeyValue.ENUM_人口标签_居家养老补助);
end

rule "删除残疾补助标签"
	salience 15 
when
	FuseLabelAttribute(value==EnumKeyValue.ENUM_人口标签_残疾补助);
	not FuseLeafAttribute(name==PeopleItem.残疾人补助信息_补助类型,sqlValue==EnumKeyValue.ENUM_残疾人补助枚举_残疾补助);
then 
	removedLabelList.add(EnumKeyValue.ENUM_人口标签_残疾补助);
end
*/
rule "居家养老补助打标签"
	salience 10 
when
	//not FuseLabelAttribute(value==EnumKeyValue.ENUM_人口标签_居家养老补助);
	FuseLeafAttribute(name==PeopleItem.老人补助信息_补助类型, $value:sqlValue, $va:value);
	eval(String.valueOf(EnumKeyValue.ENUM_老人补助枚举_居家养老补助).equals(String.valueOf($value)))
then 
	OutputDisplay.showText("value:sqlValue" +  $value);
	OutputDisplay.showText("$va:value" + $va);
	addedLabelList.add(EnumKeyValue.ENUM_人口标签_居家养老补助);
end

rule "残疾补助打标签"
	salience 10 
when
	//not FuseLabelAttribute(value==EnumKeyValue.ENUM_人口标签_残疾补助);
	FuseLeafAttribute(name==PeopleItem.残疾人补助信息_补助类型,  $value:sqlValue);
	eval(String.valueOf(EnumKeyValue.ENUM_残疾人补助枚举_残疾补助).equals(String.valueOf($value)))
then 
	addedLabelList.add(EnumKeyValue.ENUM_人口标签_残疾补助);
end
