package com.abc.rule.people.ipm

import com.abc.fuse.improve.attribute.FuseAttribute;
import com.abc.relation.RecordRelation;
import  com.zhsq.biz.constant.people.PeopleItem;
import  com.zhsq.biz.constant.family.FamilyItem;
import com.abc.rrc.record.Attribute;
import com.abc.rrc.factory.AttributeFactory;
import com.zhsq.biz.family.algorithm.DataIntrospection;
import com.zhsq.biz.constant.EnumKeyValue;
import com.zhsq.biz.constant.RelationType;
import com.abc.fuse.improve.attribute.leaf.FuseLeafAttribute;
import com.zhsq.biz.common.CommonCalculation;
import com.zhsq.biz.people.algorithm.IDIntrospection;
import com.zhsq.biz.constant.DateUtils;
import com.zhsq.biz.constant.BaseConstant;
import com.abc.relation.RelationCorrelation;

global java.lang.String hostCode; 
global java.lang.String hostType;

global java.lang.String userCode;
global java.lang.String recordCode;
global java.lang.String recordName;

global java.util.List attributeList;
global java.util.List addedLabelList;
global java.util.List removedLabelList;
global java.util.List addedLabelList;
global java.util.List putFuseLeafAttributeList;
global java.util.List addedLeafAttrList;
global java.util.Map removedLeafAttrMap;
global com.abc.rrc.record.RootRecord rootRecord;
global  com.abc.fuse.improve.ops.builder.RecordRelationOpsBuilder recordRelationOpsBuilder;
global com.abc.complexus.RecordComplexus recordComplexus;

rule "人和家庭的关系放进空间2"
salience 10 
when
	eval(BaseConstant.TYPE_家庭信息.equals(hostType));
then 
		RelationCorrelation relationCorrelation = recordComplexus.getRelationCorrelation(hostCode);
		if (relationCorrelation != null) {
			relationCorrelation.getRecordRelation().forEach(recordRelation -> 
			insert(recordRelation)
			);
		}
	//激活 
	kcontext.getKnowledgeRuntime().getAgenda().getAgendaGroup( "a_家庭与人的关系" ).setFocus();
end

rule "家庭中添加成员与户主的关系one2"//第一次添加户主和成员
	agenda-group "a_家庭与人的关系"
	salience 10 
when
	 RecordRelation(type==RelationType.RR_家庭信息_户主_人口信息,left==hostCode, $huzCode:right);
	 RecordRelation(type==RelationType.RR_家庭信息_成员_人口信息,left==hostCode,right==recordCode);
	 FuseAttribute(name==PeopleItem.和户主关系, $value:attribute.sqlValue);
then 
	//添加关系
	String relationName = BaseConstant.getRelationName(String.valueOf($value));
	recordRelationOpsBuilder.putRelation(relationName,$huzCode); 
end

rule "不存在归属家庭关系置空和户主关系1"
	salience 10 
when
	not RecordRelation(type==RelationType.RR_人口信息_归属家庭_家庭信息);
	not RecordRelation(type==RelationType.RR_人口信息_户主家庭_家庭信息);
	$FA: FuseAttribute(name==PeopleItem.和户主关系, attribute.sqlValue!=null  )
then
 	Attribute attr = AttributeFactory.newInstance(PeopleItem.和户主关系, null);
	attributeList.add(attr);
end


